apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: backend
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nodejs:latest
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: MONGODB_PORT
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: nodejs-config
              key: RABBITMQ_PORT
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: MONGODB_USER
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: MONGODB_PASSWORD
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodejs-secrets
              key: RABBITMQ_PASSWORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
