apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: rabbitmq
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: http
  selector:
    app: rabbitmq
  type: LoadBalancer
